ghga_metadata_version: 0.10.0
default_settings:
  header_row: 1
  start_row: 7
  start_column: 1
worksheets:
  - settings:
      end_column: 6
      name: analyses
    sheet_name: Analysis
  - settings:
      end_column: 8
      name: analysis_process_output_files
    sheet_name: AnalysisProcessOutputFile
  - settings:
      end_column: 5
      name: analysis_processes
    sheet_name: AnalysisProcess
  - settings:
      end_column: 9
      name: biospecimens
    sheet_name: Biospecimen
  - settings:
      end_column: 9
      name: conditions
    sheet_name: Condition
  - settings:
      end_column: 3
      name: data_access_committees
    sheet_name: DataAccessCommittee
  - settings:
      end_column: 8
      name: data_access_policies
    sheet_name: DataAccessPolicy
  - settings:
      end_column: 5
      name: datasets
    sheet_name: Dataset
  - settings:
      end_column: 8
      name: individuals
    sheet_name: Individual
  - settings:
      end_column: 14
      name: library_preparation_protocols
    sheet_name: LibraryPreparationProtocol
  - settings:
      end_column: 9
      name: publications
    sheet_name: Publication
  - settings:
      end_column: 8
      name: sample_files
    sheet_name: SampleFile
  - settings:
      end_column: 10
      name: samples
    sheet_name: Sample
  - settings:
      end_column: 7
      name: sequencing_experiments
    sheet_name: SequencingExperiment
  - settings:
      end_column: 8
      name: sequencing_process_files
    sheet_name: SequencingProcessFile
  - settings:
      end_column: 10
      name: sequencing_processes
    sheet_name: SequencingProcess
  - settings:
      end_column: 20
      name: sequencing_protocols
    sheet_name: SequencingProtocol
  - settings:
      end_column: 6
      name: studies
    sheet_name: Study
  - settings:
      end_column: 8
      name: study_files
    sheet_name: StudyFile
  - settings:
      end_column: 4
      name: trios
    sheet_name: Trio
