[project]
# please adapt to package name
name = "ghga_transpiler"
version = "3.0.0"
description = "GHGA-Transpiler - excel to JSON converter"
dependencies = [
    "openpyxl >= 3.1.2, == 3.*",
    "defusedxml >= 0.7, == 0.*",
    "pydantic >=2, <3",
    "PyYAML ~= 6.0",
    "semver == 3.*",
    "schemapack == 2.0.0-alpha.4",
    'exceptiongroup>=1.0.0; python_version < "3.11"',
    'tomli>= 2.0.0; python_version < "3.11"',
    'eval-type-backport==0.2.0; python_version < "3.10"'
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/ghga-transpiler"

[project.scripts]
# please adapt to package name
ghga-transpiler = "ghga_transpiler.__main__:run"
