[project]
name = "ghga_transpiler"

version = "2.3.0"
description = "GHGA-Transpiler - excel to JSON converter"
dependencies = [
    "typer >= 0.12",
    "openpyxl >= 3.1.2, == 3.*",
    "defusedxml >= 0.7, == 0.*",
    "pydantic >=2.6, <3",
    "PyYAML ~= 6.0",
    "semver == 3.*",
    'exceptiongroup>=1.0.0; python_version < "3.11"',
    'tomli>= 2.0.0; python_version < "3.11"',
    'eval-type-backport==0.2.0; python_version < "3.10"',
    "click==8.1.0",
    'importlib-metadata>=4.4; python_version < "3.10"'
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-transpiler"

[tool.setuptools.package-data]
"ghga_transpiler.configs" = ["*.yaml"]

[project.scripts]
ghga-transpiler = "ghga_transpiler.__main__:run"
