[project]
name = "ghga_transpiler"
version = "2.1.2"
description = "GHGA-Transpiler - excel to JSON converter"
dependencies = [
    "typer >= 0.12",
    "openpyxl >= 3.1.2, == 3.*",
    "defusedxml >= 0.7, == 0.*",
    "pydantic >=2, <3",
    "PyYAML ~= 6.0",
    "semver == 3.*"
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-transpiler"

[project.scripts]
ghga-transpiler = "ghga_transpiler.__main__:run"
