name: Call PyPI publish workflow
on:
  push:
    # types: [published]
jobs:
  call-pypi-publish:
    uses: ghga-de/gh-action-pypi/.github/workflows/pypi_publish.yml@v2.0.0
    with:
      package_version: 2.1.4
      test_pypi: "true"
      python_latest: false
    secrets: inherit
